name: Deploy to Firebase Hosting on PR
'on': pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instalar dependências
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Configurar autenticação com o Firebase
      - name: Set up Firebase authentication
        run: |
          echo "${{ secrets.FOUR_LANGUAGE_CREDENTIALS }}" > ${{ runner.temp }}/service-account.json
          echo "export GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/service-account.json" >> $GITHUB_ENV

      # Deploy para Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
        run: firebase deploy --only hosting
